### ISSUE TITLE
Spillover matrix visualization issue

### ISSUE THREAD

**Issue by PingjunChen** [BodenmillerGroup/IMCDataAnalysis#22]
Hey,

I followed [this spillover correction tutorial](https://bodenmillergroup.github.io/IMCDataAnalysis/spillover-correction.html ) to conduct the spillover analysis on our data.  The heatmap in section 6.1.4 still contains all the antibodies from 113 to 176, while section 6.1.5 showcases the spillover matrix missed some antibodies from 172 to 176. After carefully checking the code, I found out some of them are masked out by the ``is_bc``, and I set ``rowData(sce)$is_bc <- TRUE`` after "apply the estimated cutoffs" in section 6.1.4, then the spillover matrix contains all antibodies. Are these antibodies (172 to 176 in the demo figure) missing in the spillover matrix performed on purpose? and does my way of taking all antibodies back reasonable or not? since I'm not fully understand the underlying principles yet, and I assume we need to have all the antibodies covered in the generated spillover matrix when performing visualization, though I noticed the saved CSV file in section 6.1.6 containing all antibodies' information.

**Comment by nilseling** [comment]
Hi @PingjunChen 
this is a known issue in CATALYST (see [here](https://github.com/HelenaLC/CATALYST/issues/247)) and still needs to be fixed. Since it's only part of the visualization I'm not so fussed about it at the moment but will come back to trying to circumvent the issue at some point. If your fix works for you then it's great!

**Comment by nilseling** [comment]
Closing as this is resolved
