### ISSUE TITLE
Cell type classification

### ISSUE THREAD

**Issue by rahilgholami** [BodenmillerGroup/IMCDataAnalysis#33]
In file `08-phenotyping.Rmd`, in `cell type classification` section, when transferring labels to SPE object (lines 633-636), I get an error originates from variable `cur_labels`. It seems that `names(cur_labels)` includes some cell IDs which don't exist in `names(spe_labels)` which shouldn't be the case according to my understanding of the code because I think `names(cur_labels)` should be a subset of `names(spe_labels)`. I would appreciate it if you could help me figure out why it could happen.

**Comment by nilseling** [comment]
Hey @rahilgholami 

thanks for raising this! It happens when the data that you labelled is different from the data that you are currently working with. In this specific example, when switching from `steinbock v0.13.5` to `steinbock v0.14.1` the segmentation changed. This meant I had to re-generate the cell labels (old ones [here](https://zenodo.org/record/6670610), new ones [here](https://zenodo.org/record/6810879)) using the [this script](https://github.com/BodenmillerGroup/IMCDataAnalysis/blob/main/scripts/transfer_labels.R).

Could you please check that you have downloaded the newest files? Your fix might cause downstream issues as the cell IDs won't match between different segmentation results.

**Comment by rahilgholami** [comment]
Thank you for the reply @nilseling 

In fact I am using cell labels downloaded from the link referenced in [03-prerequisites.Rmd](https://github.com/BodenmillerGroup/IMCDataAnalysis/blob/main/03-prerequisites.Rmd) which is none of the ones you mentioned.

**Comment by nilseling** [comment]
Sorry, I just pushed a new link, however the gated cells didn't change. Any gated cells from `v0.2.x` will be fine. So if you download all files from the current links the classification should work. At least the workflow build on Friday (https://github.com/BodenmillerGroup/IMCDataAnalysis/actions/runs/3020913549). But let's wait a bit and see if the new build also passes.

**Comment by rahilgholami** [comment]
I really appreciate your help!

**Comment by nilseling** [comment]
Hi @rahilgholami 

the newest build passed (https://github.com/BodenmillerGroup/IMCDataAnalysis/actions/runs/3053354597) so the classification seems to work if you are using the newest files. Could you please try again and let me know if the issue still persists? 
Best,

Nils

**Comment by rahilgholami** [comment]
Hi @nilseling 

I ran with the newest files, classification worked perfectly!

**Comment by nilseling** [comment]
Great :) closing now
