### ISSUE TITLE
spillover correction

### ISSUE THREAD

**Issue by rahilgholami** [BodenmillerGroup/IMCDataAnalysis#65]
Hi @nilseling 

My question is about spillover correction. Does the spillover signal get measured in the primary channel, even though it is detected in a neighbouring channel as well?

If yes, it would indeed imply that there is no decrease in the observed intensity of the primary channel that needs to be restored during spillover correction. In this case, would the estimated true signal be consistently lower than the observed signal, indicating that the spillover correction successfully removes the contribution from neighbouring channels without affecting the intensity of the primary channel?
In the non-negative least square optimisation, while the non-negativity constraint ensures that negative values are not present in the estimated true signal, it does not guarantee that the estimated true signal will consistently be lower than the observed signal.

Thank you in advance,
Rahil

**Comment by nilseling** [comment]
Hi @rahilgholami,

I'm not quite sure what you mean. Also tagging @HelenaLC here. Have a look at the original publication how signal spillover is estimated: https://pubmed.ncbi.nlm.nih.gov/29605184/. To estimate the spillover you observe signal in (empty) channels neighboring the primary channel where a metal was spotted. Based on this, the spillover matrix is computed and the nnls approach corrects the signal in neighboring channels coming from the primary channel.

**Comment by rahilgholami** [comment]
Thank you for your swift reply.

What I mean is that, spillover correction is primarily aimed at removing or reducing unwanted spillover contributions from neighbouring channels. Can we see some level of signal enhancement after spillover correction?

**Comment by nilseling** [comment]
Yes, have a look at the examples here: https://bodenmillergroup.github.io/IMCDataAnalysis/spillover-correction.html#single-cell-data-compensation and https://bodenmillergroup.github.io/IMCDataAnalysis/spillover-correction.html#image-compensation. You can see that the spillover Yb173 (primary channel) --> Yb174 (neighboring channel) was correctly removed.

**Comment by rahilgholami** [comment]
Thank you for the example.

After spillover correction, the expected outcome is typically a reduction in the signal of the affected channel rather than an increase because the correction process is designed to remove or reduce the spillover contribution. Have you ever encountered instances where there is a signal increment observed after spillover correction?

**Comment by nilseling** [comment]
Not that I remember - but I haven't numerically tested all corrected values. In theory this should not be the case. Maybe @HelenaLC has more insights as this question refers more to the `CATALYST` package.

**Comment by rahilgholami** [comment]
Thank you for your explanation and sharing your knowledge.
Based on my understanding, the optimization problem does not appear to include any constraints that explicitly address this issue. I am hopeful that @HelenaLC will come across this post and provide me with further insights and clarifications.

**Comment by HelenaLC** [comment]
Hm... My intuition here is that we can not say "the expected outcome is typically a reduction in the signal of the affected channel rather than an increase because the correction process is designed to remove or reduce the spillover contribution". 

Think of a simple example: 2 channels, A spill 5% into B. If we were to simply remove the artefactual signal, we will lose 5% of ion counts / fluorescent intensity measured. Instead, we remove artefactual signal in some places, and add back signal in others (in the mock example, we assume 5% of B stem from A, so we'd want to account for this by increasing A's signal).

Of course, reality is much more complex, i.e., there's a matrix of interactions and it is not as trivial to think about this in terms for simply removing X and adding Y... In detail, the NNLS optimization aims to *correct* signals (globally) according to ... (see [5 Compensation](https://www.bioconductor.org/packages/release/bioc/vignettes/CATALYST/inst/doc/preprocessing.html) for details on *retrieval of real signal*), where "correct" doesn't mean only remove.

![image](https://github.com/BodenmillerGroup/IMCDataAnalysis/assets/14542264/dfe4fe69-1a35-462b-a49c-1fcd2b711079)

**Comment by nilseling** [comment]
I had a look at the example data as presented in the book and did not find a marker for which the intensity increased after spillover correction. But this is not systematically tested... For me it's enough to visualize the data pre-/post-compensation to make sure the spillover is corrected.

**Comment by rahilgholami** [comment]
Thank you @HelenaLC so much for your clear and insightful explanation.

**Comment by nilseling** [comment]
I will close this now. Please open a new issue if you run into problems.
