### ISSUE TITLE
silhouette width score (Cell Phenotyping)

### ISSUE THREAD

**Issue by wqcho00** [BodenmillerGroup/IMCDataAnalysis#75]
Hi,
I am following the IMC Data Analysis Workflow on my data. Thanks for the amazing and easy-to-follow workflow so far. I have a question regarding the metrics used to estimate the cluster stability. I'd just like to confirm, is silhouette width score the same as the commonly known silhouette score? If they are the same, then the range should also be -1 to 1.. But in the vignette, when selecting the best parameters for the clusters, is there a reason why the average silhouette width scores are so low (~0)

**Comment by nilseling** [comment]
Hi @wenqi-cho 

yes, it is. Please have a look at the [bluster vignette](https://bioconductor.org/packages/release/bioc/vignettes/bluster/inst/doc/diagnostics.html) and the help at `?approxSilhouette` for all details. 
I cannot dive you a definite answer why the scores are so low as there could be multiple reasons:

1. IMC data is not easily separable into clusters due to imperfect segmentation and lateral spillover.
2. The dataset is small
3. Sample effects can influence clustering

I'd see this metric as a rough guide but in-depth analysis of the resulting clusters, quality control and visualisation of cluster labels on composite images will tell you if you detected the right cell phenotypes. 
Please close this issue if it's resolved.

**Comment by wqcho00** [comment]
Ah alright, thanks for the information!
